image: toolchain

build:
    tags:
        - docker
    script:
        - make clean malta
        - make
    artifacts:
        paths:
        - kernel/build/gzOS.elf
        - kernel/initrd.cpio
        - kernel/flash.bin

